repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        name: check for added large files
        description: prevents giant files from being committed.
        entry: check-added-large-files
        language: python
        stages: [commit, push, manual]

  - repo: local # Use a local repository
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        entry: actionlint
        language: golang
        additional_dependencies:
          [github.com/rhysd/actionlint/cmd/actionlint@v1.6.23]
        types: ['yaml']
        files: '^.github/workflows/'
