version: '2'
services:
  angular:
    image: ${DOCKER_REG_PRIVATE}/orcid/registry/orcid-web-frontend-${BUILD_ENV:-local}:${TAG:-0.0.1}
    #entrypoint: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        build_env: ${BUILD_ENV:-local}
    ports:
      - 0.0.0.0:13105:8080
