name: bld_all_yarn

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'version tag to use'
        required: false
        default: "latest"
        type: string
      git_checkout:
        description: 'branch or tag to checkout for building'
        required: false
        default: "main"
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch amount or try gitlog'
        required: false
        default: "gitlog"
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to use:'
        required: false
        default: "latest"
        type: string
      git_checkout:
        description: 'Branch or tag to checkout for building:'
        required: false
        default: "main"
        type: string
      bump:
        description: |
          How to optionally bump the semver version ( Major.Minor.Patch ) : gitlog = git log will be searched for
          '#major #minor #patch'
        required: false
        options:
        - gitlog
        - patch
        - minor
        - major
        type: choice

jobs:

  bld_prod:
    uses: ./.github/workflows/bld_yarn.yml
    with:
      artifact_name: prod

#   bld_sandbox:
#     uses: ./.github/workflows/bld_yarn.yml
#     with:
#       artifact_name: sandbox
# 
#   bld_qa:
#     uses: ./.github/workflows/bld_yarn.yml
#     with:
#       artifact_name: qa
# 
#   bld_int:
#     uses: ./.github/workflows/bld_yarn.yml
#     with:
#       artifact_name: int
# 
