name: pr

# read-only repo token
# no access to secrets

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:

  workflow_dispatch:

# cancel running job if another commit comes in
concurrency:
  group: pr-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
 blar:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'blar'
