name: pushmain

on:
  push:
    branches:
      - main
    # Ignore changes that are made as part of the rel_tag workflow to avoid infinite loop
    paths-ignore:
      - CHANGELOG.md
    # Ignore workflow changes
      - '.github/**'
    # Ignore changes that are made as part of the rel_tag workflow to avoid infinite loop
    tags-ignore:
      - '**'

# cancel running job if another commit comes in
concurrency:
  group: pushmain-${{ github.ref }}-1
  cancel-in-progress: false

jobs:
  format_prettier:
    uses: ./.github/workflows/format_prettier.yml
    secrets: inherit # pass all secrets for pushing
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml
    needs:
      - format_prettier

